import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@components/Provider";
import { Box, Container } from "@mui/material";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Box
          component="main"
          sx={{
            overflow: "auto",
            paddingTop: {
              xs: "8rem",
              md: "0",
            },
            paddingX: {
              xs: "1rem",
              md: "2rem",
            },
          }}
        >
          <Provider>
            <Navbar />
            {children}
          </Provider>
        </Box>
      </body>
    </html>
  );
}
